#index:
#    path: /
#    controller: App\Controller\DefaultController::index


index:
  path:       /
  controller: App\Controller\Main\PostController::getAllPosts

sendCommentToPost:
  path:       /post/{id}/sendComment
  controller: App\Controller\Main\IndexController::sendComment

  ##############################################################################
  ###############            Post routes                    ####################

search:
  path:       /search
  controller: App\Controller\Main\PostController::search

allPostsRandom:
  path:       /random
  controller: App\Controller\Main\PostController::getAllPostsByRandom

allFollowedUsersPost:
  path:       /followed
  controller: App\Controller\Main\PostController::getAllPostsOfFollowedUsers

publish:
  path:       /publish
  controller: App\Controller\Main\PostController::postCreation

successPost:
  path:       /success
  controller: App\Controller\Main\PostController::successPost


postById:
  path:       /post/{id}
  controller: App\Controller\Main\PostController::getPostById

postsOfCategory:
  path:       /category/{category}
  controller: App\Controller\Main\PostController::getAllPostsOfCategory

deletePostNormalUser:
  path:       /deletePost
  controller: App\Controller\Main\PostController::deletePost

votePost:
  path:       /post/reaction/{postId}/{reaction}
  controller: App\Controller\Main\PostController::votePost

voteComment:
  path:       /comment/reaction/{commentId}/{reaction}
  controller: App\Controller\Main\PostController::voteComment




  ##############################################################################
  ###############            User routes                    ####################

successUser:
  path:       /success
  controller: App\Controller\Main\UserController::successUser

profile:
  path:       /profile/{username}
  controller: App\Controller\Main\UserController::getUserProfile

profileShowPosts:
  path:       /profile/{username}/posts
  controller: App\Controller\Main\UserController::getUserProfilePosts

profileShowComments:
  path:       /profile/{username}/comments
  controller: App\Controller\Main\UserController::getUserProfileComments

register:
  path:       /register
  controller: App\Controller\Main\UserController::userCreation

followUser:
  path:       /follow/{username}
  controller: App\Controller\Main\UserController::followUser

unfollowUser:
  path:       /unfollow/{username}
  controller: App\Controller\Main\UserController::unfollowUser


account:
  path:       /account
  controller: App\Controller\Main\UserController::accountIndex

accountAportations:
  path:       /account/aportations
  controller: App\Controller\Main\UserController::accountUserAportations

accountNetwork:
  path:       /account/network
  controller: App\Controller\Main\UserController::accountNetwork

accountEdit:
  path:       /account/edit
  controller: App\Controller\Main\UserController::accountEdit

accountEditForm:
  path:       /account/editForm
  controller: App\Controller\Main\UserController::accountEditForm

sendMessages:
  path:       /account/sendMessages
  controller: App\Controller\Main\UserController::accountSendMessage

sendMessagesTo:
  path:       /account/sendMessages/{username}
  controller: App\Controller\Main\UserController::accountSendMessageTo

newChat:
  path:       /account/newChat
  controller: App\Controller\Main\UserController::createChat

messages:
  path:       /messages
  controller: App\Controller\Main\UserController::chatList

login:
  path:       /login
  controller: App\Security\AppCustomAuthenticator::onAuthenticationSuccess()
##############################################################################
###############            ADMIN PANEL METHODS            ####################
###############                                           ####################
##############################################################################
listAllApiMethods:
  path:       /admin
  controller: App\Controller\Main\AdminController::getAllApiRoutes

listAllUsers:
  path:       /admin/listAllUsers
  controller: App\Controller\Main\AdminController::getAllUsers

listPostsOfUser:
  path:       /admin/listPostsOfUser/{username}
  controller: App\Controller\Main\AdminController::getPostsOfUser

listAllPosts:
  path:       /admin/listAllPosts
  controller: App\Controller\Main\AdminController::getAllPosts

listAllCategories:
  path:       /admin/listAllCategories
  controller: App\Controller\Main\AdminController::getAllCategories

createCategories:
  path:       /admin/createCategories
  controller: App\Controller\Main\AdminController::categoryCreation

newCategory:
  path:       /admin/newCategory
  controller: App\Controller\Main\AdminController::newCategory

createRandomUsers:
  path:       /admin/randomUsers
  controller: App\Controller\Main\AdminController::newRandomUsers

createRandomPosts:
  path:       /admin/randomPosts
  controller: App\Controller\Main\AdminController::newRandomPosts

createRandomComments:
  path:       /admin/randomComments
  controller: App\Controller\Main\AdminController::newRandomComments

deleteCategory:
  path:       /admin/deleteCategory
  controller: App\Controller\Main\AdminController::deleteCategory

deletePost:
  path:       /admin/deletePost
  controller: App\Controller\Main\AdminController::deletePost

deleteUser:
  path:       /admin/deleteUser
  controller: App\Controller\Main\IndexController::deleteUser

listCommentsOfUser:
  path:       /admin/listCommentsOfUser/{username}
  controller: App\Controller\Main\AdminController::getCommentsOfUser

listAllComments:
  path:       /admin/listAllComments
  controller: App\Controller\Main\AdminController::getAllComments