#index:
#    path: /
#    controller: App\Controller\DefaultController::index


index:
  path:       /
  controller: App\Controller\Main\IndexController::getAllPosts

allPostsRandom:
  path:       /random
  controller: App\Controller\Main\IndexController::getAllPostsByRandom

publish:
  path:       /publish
  controller: App\Controller\Main\IndexController::postCreation

successPost:
  path:       /success
  controller: App\Controller\Main\IndexController::successPost

successUser:
  path:       /success
  controller: App\Controller\Main\IndexController::successUser

postById:
  path:       /post/{id}
  controller: App\Controller\Main\IndexController::getPostById

postsOfCategory:
  path:       /category/{category}
  controller: App\Controller\Main\IndexController::getAllPostsOfCategory

profile:
  path:       /profile/{username}
  controller: App\Controller\Main\IndexController::getUserProfile

profileShowPosts:
  path:       /profile/{username}/posts
  controller: App\Controller\Main\IndexController::getUserProfilePosts

profileShowComments:
  path:       /profile/{username}/comments
  controller: App\Controller\Main\IndexController::getUserProfileComments

messages:
  path:       /messages
  controller: App\Controller\Main\IndexController::getAllApiRoutes

login:
  path:       /login
  controller: App\Security\AppCustomAuthenticator::onAuthenticationSuccess()

register:
  path:       /register
  controller: App\Controller\Main\IndexController::userCreation

deletePostNormalUser:
  path:       /deletePost
  controller: App\Controller\Main\IndexController::deletePost

sendCommentToPost:
  path:       /post/{id}/sendComment
  controller: App\Controller\Main\IndexController::sendComment

votePost:
  path:       /post/reaction/{postId}/{reaction}
  controller: App\Controller\Main\IndexController::votePost
##############################################################################
###############            ADMIN PANEL METHODS            ####################
###############                                           ####################
##############################################################################
listAllApiMethods:
  path:       /admin
  controller: App\Controller\Main\AdminController::getAllApiRoutes

listAllUsers:
  path:       /admin/listAllUsers
  controller: App\Controller\Main\AdminController::getAllUsers

listPostsOfUser:
  path:       /admin/listPostsOfUser/{username}
  controller: App\Controller\Main\AdminController::getPostsOfUser

listAllPosts:
  path:       /admin/listAllPosts
  controller: App\Controller\Main\AdminController::getAllPosts

listAllCategories:
  path:       /admin/listAllCategories
  controller: App\Controller\Main\AdminController::getAllCategories

newCategory:
  path:       /admin/newCategory
  controller: App\Controller\Main\AdminController::newCategory

deleteCategory:
  path:       /admin/deleteCategory
  controller: App\Controller\Main\AdminController::deleteCategory

deletePost:
  path:       /admin/deletePost
  controller: App\Controller\Main\AdminController::deletePost

listCommentsOfUser:
  path:       /admin/listCommentsOfUser/{username}
  controller: App\Controller\Main\AdminController::getCommentsOfUser

listAllComments:
  path:       /admin/listAllComments
  controller: App\Controller\Main\AdminController::getAllComments